spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:7001/eureka/,http://eurekaserver2:7002/eureka/,http://eurekaserver3:7003/eureka/
  instance:
    instance-id: order:8003
    prefer-ip-address: true

server:
  port: 8003
env: dev